{% set name = "yaqd-ni" %}
{% set version = "2023.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yaqd_ni-{{ version }}.tar.gz
  sha256: 1f9e491d88aa4f3e7d1b1ce83622689fc64a51bedb839495f48661227bd6e31f

build:
  entry_points:
    - yaqd-ni-daqmx-tmux = yaqd_ni._ni_daqmx_tmux:NiDaqmxTmux.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - yaqd-core >=2021.3.0
    - pydaqmx
    - numpy

test:
  imports:
    - yaqd_ni
  commands:
    - pip check
    - yaqd-ni-daqmx-tmux --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq daemons for NI hardware
  dev_url: https://github.com/yaq-project/yaqd-ni
  license: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ddkohler
